const theme = {
  BackgroundBlue: "#F5F7FF",
  LightBlue: "#E6EBFF",
  MediumBlue: "#aab9ff",
  SubBlue: "#6F87FF",
  CheryBlue: "#5471FF",
  Red: "#F25555",
  Yellow: "#FFD833",
  White: "#FFFFFF",
  BackgroundGray: "#F5F5F5",
  LightGray: "#DBDCDC",
  MediumGray: "#B5B7BA",
  GrayGray: "#909398",
  DarkGray: "#5C5F66",
  BlackGray: "#292C34",
  Black: "#000",
  WebYellow: "#FCEF8C",
  StatusCorrect: "#187AFF",
  StatusError: "#F25555",
  StatusCorrectLight: "#A2C9FF",
  StatusErrorLight: "#F9BABA",
  StatusErrorSub: "#F47777",
  StatusCorrectSub: "#4694FF",
  LightMath: "#CEFFEE",
  MediumMath: "#61EAB9",
  BackgroundMath: "#E8FFF7",
  MagentaLogo: "#FF77A8",
  LightKor: "#FFDFDF",
  BackgroundKor: "#FFEFEF",
  LightEng: "#FFF1C1",
  BackgroundEng: "#FFF8E0",
  LightLogo: "#FFF196",
  BoldKor: "#F5948E",
  BoldEng: "#FFDC61",
  BoldMath: "#61EAB9",
};

export default theme;
